"""romoved used column

Revision ID: caefbe5ecc93
Revises: cbdd899921af
Create Date: 2025-12-03 06:22:34.162380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caefbe5ecc93'
down_revision: Union[str, Sequence[str], None] = 'cbdd899921af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_verification_tokens', 'used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification_tokens', sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
