"""add last email sent column

Revision ID: f73d1e61fc24
Revises: 296b909140af
Create Date: 2025-12-09 03:21:58.252541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73d1e61fc24'
down_revision: Union[str, Sequence[str], None] = '296b909140af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification_tokens', sa.Column('last_email_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_verification_tokens', 'last_email_sent_at')
    # ### end Alembic commands ###
